version: "3.8"
services:
  app:
    container_name: payments
    build: 
      args:
        - GIN_MODE=debug
        - PORT=8080
      context: .
    image: gotest:1
    command: gow run .
    networks:
      - go-net
    ports: 
      - 8080:8080
    volumes:
      - .:/app
  db:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodb-data:/data/db
    networks:
      - go-net
volumes: 
  mongodb-data:
networks:
  go-net: 